### ISSUE TITLE
Support multiple different semver major dependencies on a single crate

### ISSUE THREAD

**Issue by Nemo157** [deps-rs/deps.rs#110]
In `async-compression` I support all of Tokio's `^0.2`, `^0.3` and `^1.0` release branches as optional dependencies.

```toml
tokio-02 = { package = "tokio", version = "0.2.21", optional = true, default-features = false }
tokio-03 = { package = "tokio", version = "0.3.0", optional = true, default-features = false }
tokio = { version = "1.0.0", optional = true, default-features = false }
```

deps.rs chooses only the `^0.3` dependency to show (<https://deps.rs/crate/async-compression/0.3.8>):

![image](https://user-images.githubusercontent.com/81079/118975312-2d29ef80-b974-11eb-8ab2-7973ae221f55.png)

Probably because it is the last of the 3 in the generated `Cargo.toml`. I'm not really sure how the UI could change to support situations like this better.
