### ISSUE TITLE
Proposal: Generate reports for collections of crates

### ISSUE THREAD

**Issue by realaravinth** [deps-rs/deps.rs#116]
## Motivation
I have some libraries that look abandoned but are being used in other projects. The only changes that these libraries will see is dependency updates. My current workflow of updating dependencies across projects using `deps.rs` involves checking the badges in each project. I find this very tedious. A feature that would aggregate reports from multiple projects and present them in a single page would be really nice.

## Solution
Source code locations can be stored on a publicly accessible file called `deps.toml`. The location of this file can be submitted to the service by embedding it in the URI.

So if `deps.toml` is available at https://example.com/deps.toml, visiting https://deps.rs/collection/https%3A%2F%2Fexample.com%2Fdeps.toml would serve the aggregated report.

```toml
[sources]
shiny-robots = { github = "https://github.com/deps-rs/deps.rs/" }
conduit = { gitlab = "https://gitlab.com/famedly/conduit" }
```
>example deps.toml

Optionally, an RSS feed can be provided for each collection.

I'm willing to submit PRs to this effect.

---
P.S Thanks for the great project! deps.rs has become an integral part of my workflow :)
