### ISSUE TITLE
Workspace members not being detected

### ISSUE THREAD

**Issue by BeastLe9enD** [deps-rs/deps.rs#195]
I have a Cargo workspace with multiple crates, in my main Cargo.toml I add the members:
```TOML
[workspace]
members = ["crates/*"]
```

The deps.rs badge does not detect the crates.
My github repository: https://github.com/projectkml/tort
