### ISSUE TITLE
Platform-specific dependencies are not shown

### ISSUE THREAD

**Issue by gendx** [deps-rs/deps.rs#232]
Besides the usual `[dependencies]`, `[dev-dependencies]` and `[build-dependencies]` sections, Cargo allows specifying [per-platform dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies) with the following syntax:

```toml
[target.'cfg(windows)'.dependencies]
foo = "1.2.3"

[target.bar.dev-dependencies]
bar = "4.5.6"
```

The general syntax is `target.*.(dev-|build-)?dependencies`, where the middle part `*` may represent the platform in arbitrarily complex ways (`cfg()`, custom target, etc.).

Currently, such dependencies are not recognized by deps.rs, see [this example Cargo.toml](https://github.com/gendx/stv-rs/blob/main/Cargo.toml):

```toml
[target.'cfg(any(target_os = "android", target_os = "dragonfly", target_os = "freebsd", target_os = "linux"))'.dependencies]
nix = { version = "0.28", features = ["sched"] }
```

I don't think deps.rs should try to parse the platform part (to report for which platform there are outdated dependencies), but it would be good to report all the target-specific dependencies :)
